# Generated by Django 5.2.9 on 2025-12-19 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код КАТОТТГ"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Райони",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код КАТОТТГ"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Назва")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("O", "Область / АРК"),
                            ("K", "Місто спеціального статусу"),
                        ],
                        max_length=1,
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регіон (Область)",
                "verbose_name_plural": "Регіони (Області)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код КАТОТТГ"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Назва")),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communities",
                        to="location.district",
                        verbose_name="Район",
                    ),
                ),
            ],
            options={
                "verbose_name": "Громада",
                "verbose_name_plural": "Громади",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="location.region",
                verbose_name="Регіон",
            ),
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код КАТОТТГ"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Назва")),
                (
                    "category",
                    models.CharField(
                        choices=[("M", "Місто"), ("X", "Селище"), ("C", "Село")],
                        max_length=1,
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Широта"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Довгота"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="location.community",
                        verbose_name="Громада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Населений пункт",
                "verbose_name_plural": "Населені пункти",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CityDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код КАТОТТГ"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Назва")),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_districts",
                        to="location.settlement",
                        verbose_name="Місто",
                    ),
                ),
            ],
            options={
                "verbose_name": "Район у місті",
                "verbose_name_plural": "Райони у містах",
                "ordering": ["name"],
            },
        ),
    ]
