# Generated by Django 5.2.9 on 2025-12-19 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=2, unique=True, verbose_name="Код"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Розділ",
                "verbose_name_plural": "Розділи",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=1, unique=True, verbose_name="Код"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Секція",
                "verbose_name_plural": "Секції",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=10, unique=True, verbose_name="Код"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="kved.division",
                        verbose_name="Розділ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Група",
                "verbose_name_plural": "Групи",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=10, unique=True, verbose_name="Код"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="kved.group",
                        verbose_name="Група",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клас",
                "verbose_name_plural": "Класи",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="division",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="kved.section",
                verbose_name="Секція",
            ),
        ),
    ]
