# Generated by Django 5.2.9 on 2025-12-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionary", "0001_initial"),
        (
            "employer",
            "0002_alter_employer_brand_name_alter_employer_description_and_more",
        ),
        ("kved", "0001_initial"),
        ("location", "0001_initial"),
        ("position", "0002_jobtitle"),
        ("speciality", "0002_alter_knowledgefield_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Назва вакансії"),
                ),
                ("description", models.TextField(verbose_name="Опис вакансії")),
                (
                    "requirements",
                    models.TextField(blank=True, default="", verbose_name="Вимоги"),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, default="", verbose_name="Обов'язки"),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата від"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата до"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("UAH", "₴ (Гривня)"),
                            ("USD", "$ (Долар США)"),
                            ("EUR", "€ (Євро)"),
                        ],
                        default="UAH",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публікації"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Термін дії до"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dictionary.degree",
                        verbose_name="Освітній ступінь",
                    ),
                ),
                (
                    "education_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionary.educationlevel",
                        verbose_name="Рівень освіти",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="employer.employer",
                        verbose_name="Роботодавець",
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionary.employmenttype",
                        verbose_name="Вид зайнятості",
                    ),
                ),
                (
                    "kved",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="kved.class",
                        verbose_name="Вид діяльності (КВЕД)",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies",
                        to="location.settlement",
                        verbose_name="Місце роботи (Населений пункт)",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies",
                        to="position.position",
                        verbose_name="Посада",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="speciality.speciality",
                        verbose_name="Спеціальність",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vacancies",
                        to="dictionary.tag",
                        verbose_name="Теги / Ознаки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансія",
                "verbose_name_plural": "Вакансії",
                "ordering": ["-published_at"],
            },
        ),
    ]
