# Generated by Django 5.2.9 on 2025-12-20 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0002_jobtitle"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vacancies",
                to="position.jobtitle",
                verbose_name="Посада (Детальна назва)",
            ),
        ),
    ]
