# Generated by Django 5.2.9 on 2025-12-21 14:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_vacancysource"),
        ("vacancy", "0002_alter_vacancy_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата підтвердження"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="external_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ID повинен складатися з 15 цифр (Центр + Дата + Номер)",
                        regex="^\\d{15}$",
                    )
                ],
                verbose_name="Внутрішній номер (ID)",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="generation",
            field=models.PositiveIntegerField(default=1, verbose_name="Покоління"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="republications",
                to="vacancy.vacancy",
                verbose_name="Попередня вакансія (ланцюжок)",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="report_3pn_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата звіту 3-ПН"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vacancies",
                to="dictionary.vacancysource",
                verbose_name="Джерело",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="published_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата публікації"
            ),
        ),
    ]
