# Generated by Django 5.2.9 on 2025-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0003_vacancy_confirmed_at_vacancy_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата закриття"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активна"),
                    ("filled", "Укомплектована"),
                    ("withdrawn", "Скасована (відсутність потреби)"),
                    ("expired", "Протермінована (архів)"),
                ],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна (публічна)"),
        ),
    ]
