# Generated by Django 5.2.9 on 2025-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0004_vacancy_closed_at_vacancy_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Адреса (вулиця, будинок)",
            ),
        ),
    ]
