# Generated by Django 5.2.9 on 2025-12-20 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kved", "0001_initial"),
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Офіційна назва / ПІБ"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Бренд / Публічна назва",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{8,10}$",
                                "Код повинен містити 8 (ЄДРПОУ) або 10 (РНОКПП) цифр",
                            )
                        ],
                        verbose_name="ЄДРПОУ / РНОКПП",
                    ),
                ),
                (
                    "employer_type",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Юридична особа"),
                            ("FOP", "ФОП"),
                            ("SELF", "Самозайнятий"),
                        ],
                        default="LEGAL",
                        max_length=10,
                        verbose_name="Тип роботодавця",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Про роботодавця"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employer_logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Перевірено адміністратором"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "kved",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employers",
                        to="kved.class",
                        verbose_name="Основний КВЕД",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employers",
                        to="location.settlement",
                        verbose_name="Місцезнаходження",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Власник профілю",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employer_staff",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Персонал / Рекрутери",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роботодавець",
                "verbose_name_plural": "Роботодавці",
                "ordering": ["name"],
            },
        ),
    ]
