# Generated by Django 5.2.9 on 2025-12-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="brand_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Бренд / Публічна назва",
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Про роботодавця"
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="website",
            field=models.URLField(blank=True, default="", verbose_name="Веб-сайт"),
        ),
    ]
