# Generated by Django 5.2.9 on 2025-12-21 00:24

import core.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employer",
            "0002_alter_employer_brand_name_alter_employer_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    core.utils.upload_to, *(), **{"folder_name": "employer_logos"}
                ),
                verbose_name="Логотип",
            ),
        ),
    ]
