# Generated by Django 5.2.9 on 2025-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employer", "0003_alter_employer_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Юридична адреса / Офіс",
            ),
        ),
    ]
