# Generated by Django 5.2.9 on 2025-12-21 00:24

import core.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    core.utils.upload_to, *(), **{"folder_name": "tag_icons"}
                ),
                verbose_name="Іконка / Логотип",
            ),
        ),
    ]
