# Generated by Django 5.2.9 on 2025-12-21 14:12

import core.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_tag_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Назва"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Системний код")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=functools.partial(
                            core.utils.upload_to, *(), **{"folder_name": "source_icons"}
                        ),
                        verbose_name="Іконка / Логотип",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Джерело вакансій",
                "verbose_name_plural": "Джерела вакансій",
                "ordering": ["order", "name"],
            },
        ),
    ]
