# Generated by Django 5.2.9 on 2025-12-16 01:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Code must be 2 digits"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Knowledge Field",
                "verbose_name_plural": "Knowledge Fields",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3,10}$", "Code must be 3-10 digits"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("level", models.IntegerField(default=1)),
                ("order", models.IntegerField(default=0)),
                (
                    "knowledge_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialities",
                        to="speciality.knowledgefield",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="speciality.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Speciality",
                "verbose_name_plural": "Specialities",
                "ordering": ["knowledge_field", "level", "order", "code"],
                "indexes": [
                    models.Index(
                        fields=["knowledge_field", "code"],
                        name="speciality__knowled_bdb9be_idx",
                    )
                ],
            },
        ),
    ]
