# Generated by Django 5.2.9 on 2025-12-20 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speciality", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgefield",
            options={
                "ordering": ["order", "code"],
                "verbose_name": "Галузь знань",
                "verbose_name_plural": "Галузі знань",
            },
        ),
        migrations.AlterModelOptions(
            name="speciality",
            options={
                "ordering": ["knowledge_field", "level", "order", "code"],
                "verbose_name": "Спеціальність",
                "verbose_name_plural": "Спеціальності",
            },
        ),
        migrations.AlterField(
            model_name="knowledgefield",
            name="code",
            field=models.CharField(
                max_length=2,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{2}$", "Code must be 2 digits"
                    )
                ],
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgefield",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="knowledgefield",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3,10}$", "Code must be 3-10 digits"
                    )
                ],
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="knowledge_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialities",
                to="speciality.knowledgefield",
                verbose_name="Галузь знань",
            ),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Рівень"),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="speciality.speciality",
                verbose_name="Батьківська спеціальність",
            ),
        ),
    ]
