# Generated by Django 5.2.9 on 2025-12-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код КП"),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Клас",
                "verbose_name_plural": "Класи",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код КП"),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Розділ",
                "verbose_name_plural": "Розділи",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код КП"),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Назва")),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="position.class",
                        verbose_name="Клас",
                    ),
                ),
            ],
            options={
                "verbose_name": "Група",
                "verbose_name_plural": "Групи",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Код КП"
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Назва")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="position.group",
                        verbose_name="Група",
                    ),
                ),
            ],
            options={
                "verbose_name": "Професійна назва роботи",
                "verbose_name_plural": "Професійні назви робіт",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="class",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="position.section",
                verbose_name="Розділ",
            ),
        ),
        migrations.CreateModel(
            name="Subclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код КП"),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Назва")),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclasses",
                        to="position.class",
                        verbose_name="Клас",
                    ),
                ),
            ],
            options={
                "verbose_name": "Підклас",
                "verbose_name_plural": "Підкласи",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код КП"),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Назва")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="position.section",
                        verbose_name="Розділ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Підрозділ",
                "verbose_name_plural": "Підрозділи",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="class",
            name="subsection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="position.subsection",
                verbose_name="Підрозділ",
            ),
        ),
    ]
