# Generated by Django 5.2.9 on 2025-12-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("position", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Код КП"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=512, verbose_name="Професійна назва роботи"
                    ),
                ),
                (
                    "zkpptr_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Код ЗКППТР"
                    ),
                ),
                (
                    "etkd_issue",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Випуск ЄТКД"
                    ),
                ),
                (
                    "dkhp_issue",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Випуск ДКХП"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_titles",
                        to="position.group",
                        verbose_name="Група (КП)",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_titles",
                        to="position.position",
                        verbose_name="Професійна назва (КП)",
                    ),
                ),
                (
                    "subclass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_titles",
                        to="position.subclass",
                        verbose_name="Підклас (КП)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Детальна назва роботи",
                "verbose_name_plural": "Детальні назви робіт",
                "ordering": ["code", "name"],
            },
        ),
    ]
