# Generated by Django 5.2.9 on 2025-12-25 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Посада / Заголовок"),
                ),
                ("description", models.TextField(verbose_name="Про себе / Досвід")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активне"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=True,
                        help_text="Якщо увімкнено, рекрутери бачитимуть лише ваш досвід без контактів",
                        verbose_name="Анонімний профіль",
                    ),
                ),
                (
                    "expected_salary",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Очікувана зарплата (грн)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, verbose_name="Повідомлення від рекрутера"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Очікує"),
                            ("APPROVED", "Схвалено"),
                            ("REJECTED", "Відхилено"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="resume.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запит контактів",
                "verbose_name_plural": "Запити контактів",
                "unique_together": {("resume", "recruiter")},
            },
        ),
    ]
