# Generated by Django 5.2.9 on 2025-12-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("CANDIDATE", "Шукач"), ("RECRUITER", "Рекрутер")],
                default="CANDIDATE",
                max_length=10,
                verbose_name="Тип користувача",
            ),
        ),
    ]
